site_name: nf-binder-design
site_url: https://australian-protein-design-initiative.github.io/nf-binder-design
repo_url: https://github.com/Australian-Protein-Design-Initiative/nf-binder-design
site_description: nf-binder-design - Nextflow pipelines for de novo protein binder design
site_author: pansapiens

nav:
  - Home: index.md
  - Setup: setup.md
  - Workflows:
      - RFdiffusion: workflows/rfdiffusion.md
      - RFdiffusion NIM: workflows/rfd-nim.md
      - RFdiffusion3: workflows/rfd3.md
      - BindCraft: workflows/bindcraft.md
      - Germinal: workflows/germinal.md
      - BoltzGen: workflows/boltzgen.md
      - Boltz Pulldown: workflows/boltz-pulldown.md
  - Subworkflows:
      - FoldSeek: subworkflows/foldseek.md
  - Extra:
      - Examples: https://github.com/Australian-Protein-Design-Initiative/nf-binder-design/blob/main/examples/README.md
      - Development: extra/development.md
      - Utility Scripts: extra/utility-scripts.md
      - M3 HPC Examples: extra/m3-hpc-examples.md
      - Pawsey Setonix Examples: extra/pawsey-setonix.md
  - Testing: testing.md
  - Release history: changelog.md

plugins:
  - search
  - mike
#  - macros

# theme:
#   name: material
#   palette:
#     primary: teal
#     accent: deep purple
#   icon:
#     logo: material/tools
#   favicon: images/favicon.ico
#   features:
#     - search.suggest
#     - toc.follow
#     #- navigation.tabs
#     #- navigation.tabs.sticky

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - json
    - python
    - bash
    - groovy
  #logo: images/favicon.ico

extra_css:
  - styles.green.css
  #- styles.purple.css
  #- styles.indigo.css

extra:
  manifest: manifest.webmanifest
